/**
 * @file
 * Binding Component implementation automatically generated by
 * the Social Communication Platform.
 *
 * Characteristics:
 * - Type: AMQP publisher.
 * - Social Communication Platform Bus: AMQP.
 */

var amqp = require('amqplib/callback_api');
var conf = require('./conf/amqp-sender.conf');

/**
 * Sends a message to the Social Communication Platform Bus.
 * Protocol: AMQP.
 * @param {string} msg - The message to send.
 */
exports.post = function(msg) {
    connection = 'amqp://' + conf.user + ':' + conf.password +
        '@' + conf.address + ':' + conf.port;
    amqp.connect(connection, function(err, conn) {
        conn.createChannel(function(err, ch) {
            ex = conf.exchange.name;
            ch.assertExchange(ex, conf.exchange.type, {
                durable: true
            });
            ch.publish(ex, '', new Buffer(msg));
            console.log(" [x] Sent %s", msg);
        });
    });
};
